---

- include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: 'Ensures databases are created'
  mysql_db:
    login_host: 'localhost'
    login_port: 3306
    login_user: 'root'
    login_password: "{{ root_password }}"
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ mysql_databases }}"
