---

- name: 'Redhat | Ensures yum repo is installed'
  yum:
    name: 'http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm'
    state: present
  become: true

- debug:
    msg: "version is {{ version }}"

- name: 'RedHat | Ensures mysql version 5.6 is installed'
  yum:
    name: 'mysql-community-server'
    disablerepo: 'mysql57-community'
    enablerepo: 'mysql56-community'
  when: version == '5.6'
  become: true

- name: 'RedHat | Ensures mysql version 5.5 is installed'
  yum:
    name: 'mysql-community-server'
    disablerepo: 'mysql57-community'
    enablerepo: 'mysql55-community'
  when: version == '5.5'
  become: true

- name: 'RedHat | Ensures mysql version 5.7 is installed'
  yum:
    name: 'mysql-community-server'
  when: version == '5.7'
  become: true

- name: 'Redhat | Ensures operating systems dependencies are installed'
  yum:
    pkg: "{{ item }}"
    state: latest
  become: true
  with_items:
    - 'mysql-community-devel'

- name: 'Ensures python dependencies are installed'
  pip:
    name: "{{ item }}"
    state: 'latest'
  with_items:
    - MySQL-python
  become: true

- name: 'Ensures mysql service is running'
  service:
    name: 'mysql'
    state: 'restarted'
  become: true
  when: version == '5.6'

- name: 'Ensures mysqld service is running'
  service:
    name: 'mysqld'
    state: 'restarted'
  become: true
  when: version != '5.6'

- name: 'Redhat | Ensures root temporary password is known'
  command: bash -c 'cat /var/log/mysqld.log |grep "A temporary password is generated for" /var/log/mysqld.log'
  register: temp_password_line

- debug:
    msg: "temp password is {{ temp_password_line.stdout_lines[0].split(': ')[1] }}"

- name: 'Redhat | Ensures root password is set'
  command: "mysql --connect-expired-password -u root -p\"{{ temp_password_line.stdout_lines[0].split(': ')[1] }}\" --execute=\"SET PASSWORD FOR 'root'@'localhost' = PASSWORD('{{ root_password }}');\""
